[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[build.environment]
  # OpenAI API Configuration - Set this in Netlify dashboard instead
  # OPENAI_API_KEY = "your-api-key-here"

[functions]
  directory = "netlify/functions"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers for video files
[[headers]]
  for = "/vids/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "video/mp4"
    Access-Control-Allow-Origin = "*"

# Headers for GLB/3D model files
[[headers]]
  for = "/img/*.glb"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

# Headers for external model-viewer script
[[headers]]
  for = "https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
